### ISSUE TITLE
Pycharm is unresponsive if plugin window opened first time

### ISSUE THREAD

**Issue by sashgorokhov** [maff91/Coding-Counter#1]
```
PyCharm 2018.3.3 (Professional Edition)
Build #PY-183.5153.39, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
Coding Counter v0.3

I open pycharm and start code, and then some time later i open Coding Counter tool window and whole pycharm freezes. It not unfreeze in reasonable time (i waited 2 mins), so i kill it via task manager. Then when i start pycharm again and open Coding Counter, everything goes fine and it shows stats.

**Comment by maff91** [comment]
Hi @sashgorokhov, thank you for reporting!
I'll take a look in following days. Unfortunately, I won't be able to test on professional edition, but I'll give it a try with community edition.

**Comment by maff91** [comment]
@sashgorokhov, I installed a trial of the exact PyCharm version on my Windows machine and don't see any issues with the plugin.

![pycharm](https://user-images.githubusercontent.com/8473363/51709485-26eb0900-202f-11e9-9d4b-7b0f476e2611.png)

**Comment by sashgorokhov** [comment]
@maff91 Can be the issue with number of chars typed? At the moment of opening plugin window i usually see 2-5K chars typed with all time chars typed > 50K and growing.

**Comment by maff91** [comment]
@sashgorokhov You mean when you open the plugin window:
1. The IDE freezes.
2. In meanwhile,  "All time chars typed" keeps growing while you're not typing?

**Comment by sashgorokhov** [comment]
@maff91 no, not exactly. I click on plugin window button, and everything freeze. I kill pycharm, start it again, open window and everything fine and i see my numbers. I checked task manager and noticed that pycharm does not consume much CPU or RAM, so its not a performance or some kind of heavy calculations issue... 

I checked and found that pycharm has noticed that freeze and wrote a thead dump. So handy! 
Here it is, a thead dump from my latest freeze 
https://drive.google.com/open?id=1Bct_V2gT9I9LVNb1PEnnWfRBbrUf56fx
hope that helps

**Comment by maff91** [comment]
@sashgorokhov The thread dump is indeed very helpful. It precisely pinpoints the problem. I was updating UI from a background thread which apparently causes a deadlock on "AWT-EventQueue". The solution seems straightforward, I just need to post the UI update on the EventQueue or main thread. 

Thank you, I'll ping you as soon as the new version is ready.

**Comment by maff91** [comment]
@sashgorokhov I deployed a new version (0.4) , it's supposed to be available within 2 days (JetBrains review process).
